return {}
-- return {
--   'xiyaowong/transparent.nvim',
--   groups = {
--     'Normal',
--     'NormalNC',
--     'Comment',
--     'Constant',
--     'Special',
--     'Identifier',
--     'Statement',
--     'PreProc',
--     'Type',
--     'Underlined',
--     'Todo',
--     'String',
--     'Function',
--     'Conditional',
--     'Repeat',
--     'Operator',
--     'Structure',
--     'LineNr',
--     'NonText',
--     'SignColumn',
--     'CursorLine',
--     'CursorLineNr',
--     'StatusLine',
--     'StatusLineNC',
--     'EndOfBuffer',
--   },
--   extra_groups = {
--     'NormalFloat',
--     'NvimTreeNormal',
--     'NvimTreeNormalNC',
--     'NvimTreeNormalFloat',
--     'NvimTreeEndOfBuffer',
--   },
--   config = function()
--     require('transparent').clear_prefix 'lualine'
--     -- require('transparent').clear_prefix 'NeoTree'
--     require('transparent').clear_prefix 'BufferLine'
--   end,
-- }
