RIGHT ignore
LEFT ignore
Shift+RIGHT ignore
Shift+LEFT ignore
Ctrl+RIGHT ignore
Ctrl+LEFT ignore

###

] add speed 0.1
[ add speed -0.1

UP add volume 5
DOWN add volume -5

Shift+RIGHT  no-osd seek  3 exact 
Shift+LEFT   no-osd seek -3 exact
RIGHT no-osd seek  10 exact 
LEFT  no-osd seek -10 exact
Ctrl+RIGHT no-osd seek  60 exact 
Ctrl+LEFT  no-osd seek -60 exact

WHEEL_UP        add volume 5
WHEEL_DOWN      add volume -5

v cycle sub
b cycle audio
