alang=en,eng,ru,rus
slang=en,eng
sub-auto=fuzzy

# аппаратное декодирование
hwdec=auto-safe

# запоминать позицию
save-position-on-quit=yes

# хороший профиль
profile=gpu-hq

# современный рендер
vo=gpu-next

# язык интерфейса OSD
osd-language=en

# кэш
cache=yes

#Always open the video player in full screen
fullscreen=yes

#Don't close the player after finishing the video
keep-open=yes

# быстрее открывать большие mkv
demuxer-max-bytes=50M
demuxer-max-back-bytes=25M

sub-font="Noto Sans Medium"
sub-font-size=50

sub-color="#FFFFFFFF"
sub-border-color="#FF000000"

# граница
sub-border-size=2

# тень
# sub-shadow-offset=1

# положение
sub-pos=97

# жирность
# sub-bold=yes
